const obj = {
  Jan: [],
  Feb: [],
  Mar: [],
  Apr: [],
  May: [
    { content: "food", references: [4, 9, 11, 17] },
    { content: "service", references: [4, 10, 17] },
    { content: "dinner", references: [4, 14] },
    { content: "Thai", references: [4, 5, 9, 10, 14, 17] },
    { content: "restaurant", references: [4, 9, 14, 17] },
    { content: "people", references: [4, 14] },
    { content: "friendly", references: [4] },
    { content: "line", references: [4, 14] },
    { content: "chicken", references: [4, 5, 17] },
    { content: "caramel", references: [4] },
    { content: "candy", references: [4] },
    { content: "sweet", references: [4] },
    { content: "peanut", references: [4] },
    { content: "sauce", references: [5, 10, 14] },
    { content: "holy", references: [5] },
    { content: "basil", references: [5, 9] },
    { content: "beef", references: [5, 9, 14, 17] },
    { content: "rice", references: [5, 14] },
    { content: "egg", references: [5, 9, 10, 14] },
    { content: "oyster", references: [5] },
    { content: "fish", references: [5] },
    { content: "garlic", references: [5] },
    { content: "fried", references: [9, 10, 11, 14] },
    { content: "stomach", references: [9] },
    { content: "city", references: [9, 11] },
    { content: "papaya", references: [9] },
    { content: "salad", references: [9, 14] },
    { content: "prawn", references: [9] },
    { content: "depth", references: [9] },
    { content: "bomb", references: [9] },
    { content: "lunch", references: [9] },
    { content: "star", references: [10, 14] },
    { content: "gang", references: [10] },
    { content: "band", references: [10] },
    { content: "mushroom", references: [10] },
    { content: "heat", references: [10] },
    { content: "place", references: [10, 11] },
    { content: "mule", references: [10] },
    { content: "ale", references: [10] },
    { content: "cocktail", references: [10] },
    { content: "area", references: [10] },
    { content: "tavern", references: [10] },
    { content: "compass", references: [10] },
    { content: "sangria", references: [11] },
    { content: "pumpkin", references: [11] },
    { content: "inflation", references: [11] },
    { content: "husband", references: [11] },
    { content: "coconut", references: [11] },
    { content: "tree", references: [11] },
    { content: "fruit", references: [11] },
    { content: "painting", references: [11] },
    { content: "space", references: [11] },
    { content: "atmosphere", references: [11] },
    { content: "spot", references: [11] },
    { content: "advertisement", references: [11] },
    { content: "street", references: [11, 14] },
    { content: "meat", references: [14, 17] },
    { content: "sausage", references: [14] },
    { content: "snack", references: [14] },
    { content: "interior", references: [14] },
    { content: "solid", references: [14] },
    { content: "brother", references: [14] },
    { content: "recommended", references: [14] },
    { content: "patron", references: [14] },
    { content: "famous", references: [14] },
    { content: "bias", references: [14] },
    { content: "Vietnamese", references: [14] },
    { content: "bed", references: [14] },
    { content: "tea", references: [14] },
    { content: "left", references: [14] },
    { content: "kick", references: [14] },
    { content: "meal", references: [14] },
    { content: "high", references: [14] },
    { content: "noodle", references: [17] },
    { content: "runner", references: [17] },
    { content: "couple", references: [17] },
    { content: "staff", references: [17] },
    { content: "average", references: [17] },
    { content: "master", references: [17] },
    { content: "messenger", references: [17] },
    { content: "short", references: [17] },
    { content: "shorts", references: [17] },
    { content: "boatload", references: [17] },
    { content: "garment", references: [17] },
    { content: "Summer", references: [17] },
    { content: "music", references: [17] },
    { content: "basement", references: [17] },
    { content: "establishment", references: [17] }
  ],
  Jun: [
    { content: "food", references: [0, 2, 6, 7, 12, 13, 15, 16, 18, 19] },
    { content: "place", references: [0, 7, 16, 18, 19] },
    { content: "atmosphere", references: [0, 2, 16] },
    { content: "service", references: [0, 2, 3, 12, 16, 19] },
    { content: "shrimp", references: [0, 3, 6] },
    { content: "chicken", references: [0, 1, 6] },
    { content: "painting", references: [0] },
    { content: "friendly", references: [1, 3, 19] },
    { content: "staff", references: [1, 3] },
    { content: "Thai", references: [1, 3, 6, 7, 12, 16, 18] },
    { content: "tea", references: [1, 3, 7] },
    { content: "sangria", references: [1, 8, 19] },
    { content: "pad thai", references: [1, 7, 8] },
    { content: "cocktail", references: [2, 19] },
    { content: "beverage", references: [2, 6, 12, 19] },
    { content: "beef", references: [3, 6, 7] },
    { content: "coconut", references: [3, 6, 7, 12, 13] },
    { content: "snack", references: [3, 6, 13] },
    { content: "ice", references: [3, 7] },
    { content: "people", references: [3] },
    { content: "lunch", references: [3, 12] },
    { content: "mojito", references: [6] },
    { content: "tree", references: [6, 18] },
    { content: "spice", references: [6, 12] },
    { content: "area", references: [6, 7] },
    { content: "dollar", references: [6] },
    { content: "$", references: [6] },
    { content: "rice", references: [6, 7, 12, 13, 16, 18] },
    { content: "bag", references: [6] },
    { content: "egg", references: [6] },
    { content: "ground", references: [6] },
    { content: "floor", references: [6] },
    { content: "green", references: [6, 7, 12, 13] },
    { content: "favorite", references: [6] },
    { content: "chip", references: [6] },
    { content: "chassis", references: [6, 18] },
    { content: "wing", references: [6, 18] },
    { content: "sauce", references: [6, 7] },
    { content: "peanut", references: [6] },
    { content: "meat", references: [6] },
    { content: "fried", references: [6] },
    { content: "line", references: [6, 7, 12, 13] },
    { content: "dinner", references: [6, 7, 8, 12, 13, 15, 19] },
    { content: "star", references: [6] },
    { content: "restaurant", references: [6, 7, 15, 16, 18, 19] },
    { content: "city", references: [7, 12] },
    { content: "side", references: [7, 16] },
    { content: "balance", references: [7] },
    { content: "heat", references: [7, 8] },
    { content: "meal", references: [7] },
    { content: "sweet", references: [7] },
    { content: "bud", references: [7] },
    { content: "caramel", references: [7] },
    { content: "candy", references: [7] },
    { content: "master", references: [7] },
    { content: "garlic", references: [7] },
    { content: "fatty", references: [7] },
    { content: "mustard", references: [7] },
    { content: "average", references: [7] },
    { content: "noodle", references: [7, 16] },
    { content: "chef", references: [7] },
    { content: "jurisdiction", references: [7] },
    { content: "classic", references: [7] },
    { content: "left", references: [7, 12] },
    { content: "music", references: [7] },
    { content: "jug", references: [8, 19] },
    { content: "alcohol", references: [8] },
    { content: "bill", references: [12] },
    { content: "bartender", references: [12] },
    { content: "complaint", references: [12] },
    { content: "medium", references: [12] },
    { content: "ping", references: [12] },
    { content: "spot", references: [12] },
    { content: "advertisement", references: [12] },
    { content: "tavern", references: [12, 18, 19] },
    { content: "compass", references: [12, 18, 19] },
    { content: "market", references: [15] },
    { content: "design", references: [15] },
    { content: "interior", references: [15] },
    { content: "owner", references: [16] },
    { content: "soup", references: [16, 18] },
    { content: "simile", references: [18] },
    { content: "neighborhood", references: [18, 19] },
    { content: "ethnic", references: [18] },
    { content: "hobby", references: [18] },
    { content: "red wine", references: [19] },
    { content: "dog", references: [19] },
    { content: "theater", references: [19] },
    { content: "wine", references: [19] },
    { content: "group", references: [19] },
    { content: "Summer", references: [19] },
    { content: "drinker", references: [19] },
    { content: "white", references: [19] }
  ],
  Jul: [],
  Aug: [],
  Sep: [],
  Oct: [],
  Nov: [],
  Dec: []
};
